name: language_learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # YouTube データ抽出と動画再生
  youtube_player_iframe: ^4.0.4
  video_player: ^2.7.2
  cached_network_image: ^3.3.0
  
  # State management
  provider: ^6.0.5
  
  # Network and API
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  
  # Navigation
  go_router: ^13.0.0
  
  # 外部アプリを開くための URL ランチャー
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # アセットを有効化
  assets:
    - lib/data/sample_subtitles.json